### ISSUE TITLE
About Server Installation

### ISSUE THREAD

**Issue by zyc1127** [Quidvio/Vanilla-Stoneblock#4]
Hello, Can you tell me how to install this mod on my personal server, I only installed mod without any configuration, but world spawning failed

**Comment by klinbee** [comment]
Hmmm, on your personal server, so you are hosting it? Honestly I don't know, but I would try the data pack version instead. The mod is just a wrapper for the data pack, so it would probably be better to do it that way. Maybe make a world with the data pack and upload it to the server? Unsure, as data packs are my expertise rather than servers hah

**Comment by zyc1127** [comment]
Thank you very much for your help
